jobs:
  include:
  - stage: test
    language: generic
    env: Type='virus scan'
    sudo: required
    script:
    - ./include/travis/virus-scan.sh
  - stage: test
    language: generic
    env: Type='mock build test'
    sudo: required
    services:
    - docker
    before_install:
    - docker pull centos:centos7
    script:
    - ./include/travis/run_in_centos7_docker.sh include/travis/mock_build_test.sh
  - stage: deploy
    if: branch =~ ^v\d+\.\d+\.\d+-.+$
    language: generic
    env: Type='Copr deploy'
    sudo: required
    services:
    - docker
    before_deploy:
    - docker pull centos:centos7
    - openssl aes-256-cbc -K $encrypted_253525cedcf6_key -iv $encrypted_253525cedcf6_iv -in include/copr-mfl.enc -out include/copr-mfl -d
    deploy:
      skip_cleanup: true
      provider: script
      script: ./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh
      on:
        all_branches: true
