name: CI
on: [push, pull_request]

jobs:
  check_rpm_build:
    name: Check RPM build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build rpm
        uses: ./.github/actions/copr
        env:
          SPEC: python-requests-unixsocket.spec
          WORKSPACE: ${{ github.workspace }}
          LOCAL_ONLY: true
