name: devel-release
on:
  push:
    branches:
      - master
jobs:
  push_copr_devel:
    name: Push to Copr devel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Push RPM
        uses: ./.github/actions/copr
        env:
          PROD: false
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-devel
          PACKAGE: python-requests-unixsocket
          SPEC: python-requests-unixsocket.spec
          WORKSPACE: ${{ github.workspace }}
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
